services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend:latest
    networks:
      - backend-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/backend:latest
    networks:
      - backend-network
  
networks:
  backend-network:
    driver: bridge