services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    image: 876225477961.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
    networks:
      - backend-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    image: 876225477961.dkr.ecr.ap-south-1.amazonaws.com/backend:latest
    networks:
      - backend-network
  
networks:
  backend-network:
    driver: bridge