apiVersion: v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: pranav_application
  labels:
    role: backend
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      role: backend
  strategy:
    type: RollingUpdate
    rollingParams:
      maxUnavailable: 25%
      maxSurge: 1
  template:
    metadata:
      labels:
        role: backend
        env: demo
    spec:
      containers:
        - name: backend-container
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/backend:latest
          imagePullPolicy: Always
          imagePullSecrets:
            - name: ecr-registry-secret
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_CONN_STR
              value: mongodb://mongodb-svc:27017/todo?directConnection=true
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-sec
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-sec
                  key: password
            - name: AWS_REGION
              value: ap-south-1
            - name: AWS_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: mongo-sec
                  key: account-id
          livenessProbe:
            httpGet:
              path: /ok
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ok
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1