apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: pranav-application
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      role: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  template:
    metadata:
      labels:
        role: frontend
        env: demo
    spec:
      containers:
        - name: frontend-container
          image: 876225477961.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_URL
              value: "backend:8080"