apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: pranav_application
spec:
  ports:
    - port: 3000
      protocol: TCP
    
  type: ClusterIP
  selector:
    role: frontend
