apiVersion: v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: pranav_application
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      role: frontend
  strategy:
    type: RollingUpdate
    rollingParams:
      maxUnavailable: 25%
      maxSurge: 1
  template:
    metadata:
      labels:
        role: frontend
        env: demo
    spec:
      containers:
        - name: frontend-container
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend:latest
          imagePullPolicy: Always
          imagePullSecrets:
            - name: ecr-registry-secret
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_URL
              value: "backend:8080"