name: Main Workflow
description: This workflow runs on push to the main branch and executes Docker and Terraform commands.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    docker:
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Export Environment Variables
            run: |
              echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
              echo "AWS_REGION=ap-south-1" >> $GITHUB_ENV

          - uses: pranavg2104/nginx-node-redis/.github/actions/build-container@main
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: 'ap-south-1'
              aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
